name: dental_inventory
description: Dental inventory management project.
publish_to: none
version: 1.2.3+49

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: "3.27.4"

dependencies:
  flutter:
    sdk: flutter
  animations: 2.0.11
  cached_network_image: 3.3.1
  cupertino_icons: 1.0.8
  device_info_plus: 11.3.0
  dio: 5.8.0+1
  drift: 2.18.0
  firebase_core: 3.12.0
  flutter_dotenv: 5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: 5.9.3
  flutter_speed_dial: 7.0.0
  flutter_staggered_grid_view: 0.7.0
  flutter_svg: 2.0.9
  flutter_widget_from_html: 0.16.0
  font_awesome_flutter: 10.8.0
  get: 4.7.2
  get_storage: 2.1.1
  internet_connection_checker: 1.0.0+1
  intl: 0.19.0
  laser_scanner: 0.1.5
  logger: 2.5.0
  lottie: 3.0.0
  mobile_scanner: 6.0.6
  package_info_plus: 8.2.1
  path: 1.9.0
  path_provider: 2.1.5
  pretty_dio_logger: 1.4.0
  pull_to_refresh: 2.0.0
  sqlite3_flutter_libs: 0.5.30
  url_launcher: 6.3.1
  firebase_database: 11.3.3
  wakelock_plus: 1.2.10


dependency_overrides:
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  analyzer: 5.13.0
  build_runner: 2.4.13
  change_app_package_name: 1.4.0
  dart_code_metrics: any
  drift_dev: 2.18.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - images/
    - conf/.env
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 200
        - asset: fonts/Roboto-Light.ttf
          weight: 200
        - asset: fonts/Roboto-Regular.ttf
          weight: 200
        - asset: fonts/Roboto-Medium.ttf
          weight: 300
        - asset: fonts/Roboto-Bold.ttf
          weight: 600
        - asset: fonts/Roboto-Italic.ttf
          style: italic
