name: dental_inventory
description: Dental inventory management project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: "3.13.0"

dependencies:
  flutter:
    sdk: flutter
  animations: 2.0.8
  cached_network_image: 3.3.1
  cupertino_icons: 1.0.6
  dio: 5.4.0
  firebase_core: 2.26.0
  flutter_dotenv: 5.1.0
  flutter_localizations:
    sdk: flutter
  fluttertoast: 8.2.4
  flutter_screenutil: 5.9.0
  flutter_staggered_grid_view: 0.7.0
  flutter_svg: 2.0.9
  font_awesome_flutter: 10.6.0
  get: 4.6.6
  get_storage: 2.1.1
  intl: 0.18.1
  logger: 2.0.2+1
  mobile_scanner: 4.0.0
  pretty_dio_logger: 1.3.1
  pull_to_refresh: 2.0.0
  url_launcher: 6.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.2
  analyzer: 5.13.0
  dart_code_metrics: any
  change_app_package_name: 1.1.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - images/
    - conf/.env

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 200
        - asset: fonts/Roboto-Light.ttf
          weight: 200
        - asset: fonts/Roboto-Regular.ttf
          weight: 200
        - asset: fonts/Roboto-Medium.ttf
          weight: 300
        - asset: fonts/Roboto-Bold.ttf
          weight: 600
        - asset: fonts/Roboto-Italic.ttf
          style: italic
